users:
  - name: "gouse"
    email: "pasha.gouse@bizcloudexperts.com"
    groups: ["developers", "s3-read"]
    access_key_required: true
    
  - name: "biswal"
    email: "ashutosh@bizcloudexperts.com"
    groups: ["admins", "billing"]
    access_key_required: false
    
  - name: "kodmur"
    email: "ganesh.kodmur@bizcloudexperts.com"
    groups: ["developers", "ec2-manage"]
    access_key_required: true
    
  - name: "test.user"
    email: "test.user@bizcloudexperts.com"
    groups: ["developers", "s3-read"]
    access_key_required: false